### ISSUE TITLE
Firebase als Server für Development

### ISSUE THREAD

**Issue by benCoder01** [Skn0tt/laaal.net#1]
So wie ich das sehe, kann man das Projekt nicht mit `firebase serve` standardmäßig starten.
```sh
➜  public git:(master) ✗ firebase serve

Error: Unable to authorize access to project laaal-net

Having trouble? Try firebase serve --help

```
Zwar würde ich Parcel als Entwicklungsserver empfehlen, bekomme dann aber einen Fehler über eine generics.html, die fehlt (ss. Z. 149 index.html). 

```sh
➜  public git:(master) ✗ parcel index.html
Server running at http://localhost:1234 
🚨  /home/shield/Dropbox/dev/laaal.net/public/index.html: Cannot resolve dependency './generic.html' at '/home/shield/Dropbox/dev/laaal.net/public/generic.html'
    at Resolver.resolve (/home/shield/.config/yarn/global/node_modules/parcel-bundler/src/Resolver.js:69:17)
    at <anonymous>
```

**Comment by Skn0tt** [comment]
Ich würde ungerne ein "Schwergewicht" wie Parcel im Contribution Guide erwähnen - mehr als einen stupiden Webserver braucht es nicht, ein Bundler wie Parcel ist overkill.

Was hältst du von [`serve`](https://www.npmjs.com/package/serve) oder `python -m http.server`?
Wäre leichtgewichtiger und sind beides nur einfache Webserver.

**Comment by benCoder01** [comment]
Stimmt. Hatte ich garnicht dran gedacht. Trotzdem funktioniert das meiner Meinung nach nicht mit Firebase. Ich würde außerdem vorschlagen, dass man das mit der generic.html Datei löst.

**Comment by Skn0tt** [comment]
Stimmt, das ist ein toter Link.
Firebase scheint nicht zu funktionieren, weil du nicht Mitglied des Projekts bist.
Ich fixe das mal.
